language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
install:
- make BINPREFIX= deps
- pip install coveralls
script:
- make BINPREFIX= covercheck
after_success: coveralls
notifications:
  email: false
